name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Copy config file
        run: cp testconfig/configfile/config.properties /home/runner/work/openg2p-testing/openg2p-testing/testconfig/configfile/config.properties

      - name: Copy locators file
        run: cp src/main/resources/configfiles/locators.properties /home/runner/work/openg2p-testing/src/main/resources/configfiles/locators.properties

      - name: Copy headless file
        run: testconfig/configfile/headless.properties /home/runner/work/openg2p-testing/testconfig/configfile/headless.properties

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Sanity tests
        run: mvn clean test
 
